=== heyguevara/open-quote/projects/openquote/1.2/core/core.ear/configure.war/schemas/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <xs:element name="configuration" type="Configuration"/>

    <xs:complexType name="Configuration">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="parentNamespace" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="who" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="manager" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group"/>
            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter"/>
            <xs:element name="builders" minOccurs="0" maxOccurs="1" type="Builders"/>
            <xs:element name="types" minOccurs="0" maxOccurs="1" type="Types"/>
        </xs:sequence>
        <xs:attribute name="timeout" use="required" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="Group">
        <xs:complexContent>
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
     </xs:complexType>

    <xs:complexType name="Builders">
        <xs:sequence>
            <xs:element name="builder" maxOccurs="unbounded" type="Builder"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Builder">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="factory" use="required" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
     </xs:complexType>

    <xs:complexType name="Types">
        <xs:sequence>
            <xs:element name="type" minOccurs="0" maxOccurs="unbounded" type="Type"/>
            <xs:element name="service" minOccurs="0" maxOccurs="unbounded" type="Service"/>
            <xs:element name="command" minOccurs="0" maxOccurs="unbounded" type="Command"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Service">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="required" type="availableBuilders"/>
                <xs:attribute name="key" use="optional" type="availableAccessors"/>
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Command">
        <xs:complexContent>
            <xs:extension base="Type"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Type">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="required" type="availableBuilders"/>
                <xs:attribute name="key" use="optional" type="xs:string"/>
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:complexContent mixed="true">
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:any minOccurs="0" processContents="skip"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Component">
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="availableBuilders">
        <xs:restriction base="xs:string">
            <xs:enumeration value="XSLTBuilder"/>
            <xs:enumeration value="CastorXMLBuilder"/>
            <xs:enumeration value="BeanShellBuilder"/>
            <xs:enumeration value="ClassBuilder"/>
            <xs:enumeration value="CachingClassBuilder"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="availableAccessors">
        <xs:restriction base="xs:string">
            <xs:enumeration value="com.ail.core.command.ClassAccessor"/>
            <xs:enumeration value="com.ail.core.command.BeanShellAccessor"/>
            <xs:enumeration value="com.ail.core.command.DroolsAccessor"/>
            <xs:enumeration value="com.ail.core.command.DroolsDecisionTableAccessor"/>
            <xs:enumeration value="com.ail.core.command.EJBAccessor"/>
            <xs:enumeration value="com.ail.core.command.WebServiceAccessor"/>
            <xs:enumeration value="com.ail.core.command.XSLTAccessor"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== heyguevara/open-quote/root/projects/openquote/2.0-defunct-2/core/test.jar/com/ail/coretest/TestCoreHibernatePersistenceDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 $Revision: 1.6 $
 $State: Exp $
 $Date: 2006/10/04 21:30:38 $
 $Source: /home/bob/CVSRepository/projects/core/test.jar/com/ail/coretest/TestCoreHibernatePersistenceDefaultConfig.xml,v $
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">
  <name>Default Service Invocation Configuration</name>
  <timeout>600000</timeout>
  <who>factory</who>
  <version>$Revision: 1.6 $</version>

  <types>
    <!--============================================-->
    <!--   Define the (local) component's services  -->
    <!--============================================-->
    <service name="CreateService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateCreateService</parameter>
    </service>
    <service name="UpdateService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateUpdateService</parameter>
    </service>
    <service name="LoadService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateLoadService</parameter>
    </service>
    <service name="QueryService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateQueryService</parameter>
    </service>
    <service name="OpenSessionService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateOpenSessionService</parameter>
    </service>
    <service name="CloseSessionService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.core.persistence.hibernate.HibernateCloseSessionService</parameter>
    </service>

    <!--============================================-->
    <!--   Define the (remote) component's services  -->
    <!--============================================-->
    <service name='PersistenceService' builder='ClassBuilder' key='com.ail.core.command.EJBAccessor'>
      <parameter name='JndiName'>PersistenceServer</parameter>
    </service>
        
    <!--=======================================================================-->
    <!-- Bind the default core services (above) to Commands used by Core.class -->
    <!--=======================================================================-->
    <command name="TestCreateCommand" builder="ClassBuilder" key="com.ail.core.persistence.CreateCommand">
      <parameter name="Service">CreateService</parameter>
    </command>
    <command name="TestUpdateCommand" builder="ClassBuilder" key="com.ail.core.persistence.UpdateCommand">
      <parameter name="Service">UpdateService</parameter>
    </command>
    <command name="TestLoadCommand" builder="ClassBuilder" key="com.ail.core.persistence.LoadCommand">
      <parameter name="Service">LoadService</parameter>
    </command>
    <command name="TestQueryCommand" builder="ClassBuilder" key="com.ail.core.persistence.QueryCommand">
      <parameter name="Service">QueryService</parameter>
    </command>
    <command name="TestOpenSessionCommand" builder="ClassBuilder" key="com.ail.core.persistence.OpenSessionCommand">
      <parameter name="Service">OpenSessionService</parameter>
    </command>
    <command name="TestCloseSessionCommand" builder="ClassBuilder" key="com.ail.core.persistence.CloseSessionCommand">
      <parameter name="Service">CloseSessionService</parameter>
    </command>

    <!--===================================================================================================-->
    <!-- Bind remote persistence services to the PersistenceServce (in com/ail/core/CoreDefaultConfig.xml) -->
    <!--===================================================================================================-->
    <command name="TestCreateCommandRemote" builder="ClassBuilder" key="com.ail.core.persistence.CreateCommand">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestUpdateCommandRemote" builder="ClassBuilder" key="com.ail.core.persistence.UpdateCommand">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestLoadCommandRemote" builder="ClassBuilder" key="com.ail.core.persistence.LoadCommand">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestQueryCommandRemote" builder="ClassBuilder" key="com.ail.core.persistence.QueryCommand">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestOpenSessionCommandRemote" builder="ClassBuilder" key="com.ail.core.persistence.OpenSessionCommand">
      <parameter name="Service">PersistenceService</parameter>
    </command>
    <command name="TestCloseSessionCommandRemote" builder="ClassBuilder" key="com.ail.core.persistence.CloseSessionCommand">
      <parameter name="Service">PersistenceService</parameter>
    </command>

  </types>
</configuration>

=== heyguevara/open-quote/tags/projects/builds/openquote/insurance/build-10/insurance.ear/lib/insurance.jar/com/ail/core/product/TestProduct8/RegistryDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines a test product which will always has two referrals.
 $Revision$
 $Author$
 $State$
 $Date$
 $Source$
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">
    <name>Configuration for Test Product 7</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>$Revision$</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    <parentNamespace>com.ail.core.product.TestProduct1.Registry</parentNamespace>
    
    <types>
        <service name="PolicyRule" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor" >
            <parameter name="Script"><![CDATA[
                import com.ail.financial.CurrencyAmount;
                import com.ail.financial.Currency;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                /* add two lines - just to show that this rule has been run */
                as.addFixedSum("dummyid1", "Loading", null, "total premium", new CurrencyAmount(0.0, Currency.GBP));
                as.addReferral("dummyid3", "No reason", null);
                as.addReferral("dummyid4", "No reason", null);
            ]]></parameter>
        </service>

        <type name="TestProduct8" key="com.ail.core.Type" builder="BeanShellBuilder">
            <parameter name="Extends">TestProduct1</parameter>
            <parameter name="Script"><![CDATA[
                type=new com.ail.insurance.policy.Policy();
                type.setProductTypeId("com.ail.core.product.TestProduct8");
            ]]></parameter>
        </type>
    </types>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/1.4/insurance/insurance.ear/acceptance-ejb.jar/com/ail/insurance/acceptance/AcceptanceDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Acceptance EJB configuration</name>
    <timeout>5000</timeout>
    <who>factory</who>
    <version>$Revision: 1.4 $</version>
    <types>
        <command name="ProduceDocumentation" builder="ClassBuilder" key="com.ail.insurance.acceptance.ProduceDocumentationCommandImpl">
            <parameter name="Service">com.ail.insurance.acceptance.ProduceDocumentationService</parameter>
        </command>
        <command name="PutOnRisk" builder="ClassBuilder" key="com.ail.insurance.acceptance.PutOnRiskCommandImpl">
            <parameter name="Service">com.ail.insurance.acceptance.PutOnRiskService</parameter>
        </command>
        <command name="CollectPremium" builder="ClassBuilder" key="com.ail.insurance.acceptance.CollectPremiumCommandImpl">
            <parameter name="Service">com.ail.insurance.acceptance.CollectPremiumService</parameter>
        </command>
        <command name="AcceptQuotation" builder="ClassBuilder" key="com.ail.insurance.acceptance.acceptquotation.AcceptQuotationCommandImpl">
            <parameter name="Service">com.ail.insurance.acceptance.acceptquotation.AcceptQuotationService</parameter>
        </command>
    </types>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/1.1/openquote/content/export_spaces.acp/export_spaces/content54.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default (factory) configuration use by ListProducts service.
 The configuration defines the products that are know to the system.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">
    <name>ProductCatalog configuration</name>
    <timeout>-1</timeout>
    <who>factory</who>
    <version>$Revision$</version>
    <manager>com.ail.core.product.listproducts.ListProductsService</manager>
    
    <group name="products">
        <parameter name="AIL.Base">Root of the product tree. All products extend this product.</parameter>
        <parameter name="AIL.Demo.MotorPlus">Demonstration of a multisection, multiasset product.</parameter>
        <parameter name="AIL.Demo.EquinePlus">Demonstration of a multisection, multiasset product.</parameter>
        <parameter name="AIL.Demo.IrishBrokerPI">Professional Indemnity product developed in conjunction with a London City broker.</parameter>
    </group>
</configuration>

=== heyguevara/open-quote/projects/openquote/1.4/core/integration-test.jar/com/ail/core/product/ProductCatalogDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default (factory) configuration use by ListProducts service.
 The configuration defines the products that are know to the system.
 $Revision: 1.2 $
 $State: Exp $
 $Date: 2006/07/15 15:01:44 $
 $Source: /home/bob/CVSRepository/projects/core/core.ear/core.jar/com/ail/core/product/ProductCatalogDefaultConfig.xml,v $
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">
    <name>ProductCatalog configuration</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>$Revision: 1.2 $</version>
    <manager>com.ail.core.product.listproducts.ListProductsService</manager>
    
    <group name="products">
        <parameter name="com.ail.core.product.TestProduct1"/>
        <parameter name="com.ail.core.product.TestProduct2"/>
        <parameter name="com.ail.core.product.TestProduct3"/>
    </group>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/1.2/insurance/insurance.ear/subrogation-ejb.jar/com/ail/insurance/subrogation/SubrogationDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default (factory) configuration for the Subrogation
 component. This configuration is used by the component's resetConfiguration()
 method.
 $Revision: 1.3 $
 $State: Exp $
 $Date: 2006/10/04 22:03:13 $
 $Source: /home/bob/CVSRepository/projects/insurance/insurance.ear/subrogation-ejb.jar/com/ail/insurance/subrogation/SubrogationDefaultConfig.xml,v $
-->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Subrogation component default configuration</name>
  <timeout>1000</timeout>
  <who>factory</who>
  <version>$Revision: 1.3 $</version>
  
  <types>
    <!--====================================-->
    <!--   Define the component's services  -->
    <!--====================================-->
    <service name="MakeARecoveryService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
      <parameter name="ServiceClass">com.ail.insurance.subrogation.makearecovery.MakeARecoveryService</parameter>
    </service>
    
    <!--=======================================================================-->
    <!-- Bind the default core services (above) to Commands used by Core.class -->
    <!--=======================================================================-->
    <command name="MakeARecovery" builder="ClassBuilder" key="com.ail.insurance.subrogation.makearecovery.MakeARecoveryCommand">
      <parameter name="Service">MakeARecoveryService</parameter>
    </command>
  </types>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/2.0-unified/core/core.ear/lib/core.jar/com/ail/core/CoreProxyDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the CoreProxy classes factory default configuration.
 $Revision: 1.6 $
 $State: Exp $
 $Date: 2006/07/15 15:01:44 $
 $Source: /home/bob/CVSRepository/projects/core/core.ear/core.jar/com/ail/core/CoreProxyDefaultConfig.xml,v $
-->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Core Proxy Configuration</name>
    <timeout>6000</timeout>
    <who>factory</who>
    <version>$Revision: 1.6 $</version>

    <types>
        <!-- Define other types -->
        <type name="Version" builder="ClassBuilder" key="com.ail.core.Version"/>
     <type name="BeanShellService" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor" >
          <parameter name="Script"><![CDATA[
/* make sure we can refer to our classes */
version=new com.ail.core.Version();

/* a simple bit of logic */
if (args.getX()<100) {
  args.setR(args.getX()+args.getY());
}
else {
  args.setR((2*args.getX())+args.getY());
}
            ]]></parameter>
      </type>
    </types>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/1.4/insurance/insurance.ear/quotation-ejb.jar/com/ail/insurance/quotation/QuotationDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default configuration used by the Quotation EJB component.
-->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Quotation EJB configuration</name>
    <timeout>-1</timeout>
    <who>factory</who>
    <version>$Revision: 1.4 $</version>
    <types>
        <command name="AssessRisk" builder="ClassBuilder" key="com.ail.insurance.quotation.AssessRiskCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.AssessRiskService</parameter>
        </command>
        <command name="CalculatePremium" builder="ClassBuilder" key="com.ail.insurance.quotation.CollectPremiumCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.CollectPremiumService</parameter>
        </command>
        <command name="CalculateTax" builder="ClassBuilder" key="com.ail.insurance.quotation.CalculateTaxCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.CalculateTaxService</parameter>
        </command>
        <command name="CalculateCommission" builder="ClassBuilder" key="com.ail.insurance.quotation.CalculateCommissionCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.CalculateCommissionService</parameter>
        </command>
        <command name="CalculateBrokerage" builder="ClassBuilder" key="com.ail.insurance.quotation.CalculateBrokerageCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.CalculateBrokerageService</parameter>
        </command>
        <command name="CalculateManagementCharge" builder="ClassBuilder" key="com.ail.insurance.quotation.CalculateManagementChargeCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.CalculateManagementChargeService</parameter>
        </command>
        <command name="AddQuoteNumber" builder="ClassBuilder" key="com.ail.insurance.quotation.AddQuoteNumberCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.AddQuoteNumberService</parameter>
        </command>
        <command name="AddPolicyNumber" builder="ClassBuilder" key="com.ail.insurance.quotation.AddPolicyNumberCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.AddPolicyNumberService</parameter>
        </command>
        <command name="EnforceCompliance" builder="ClassBuilder" key="com.ail.insurance.quotation.EnforceComplianceCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.EnforceComplianceService</parameter>
        </command>
        <command name="GenerateDocument" builder="ClassBuilder" key="com.ail.insurance.quotation.GenerateDocumentCommandImpl">
            <parameter name="Service">com.ail.insurance.quotation.GenerateQuoteService</parameter>
        </command>
    </types>
</configuration>
