=== heyguevara/open-quote/projects/openquote/1.2/core/core.ear/configure.war/schemas/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <xs:element name="configuration" type="Configuration"/>

    <xs:complexType name="Configuration">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="parentNamespace" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="who" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="manager" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group"/>
            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter"/>
            <xs:element name="builders" minOccurs="0" maxOccurs="1" type="Builders"/>
            <xs:element name="types" minOccurs="0" maxOccurs="1" type="Types"/>
        </xs:sequence>
        <xs:attribute name="timeout" use="required" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="Group">
        <xs:complexContent>
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
     </xs:complexType>

    <xs:complexType name="Builders">
        <xs:sequence>
            <xs:element name="builder" maxOccurs="unbounded" type="Builder"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Builder">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="factory" use="required" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
     </xs:complexType>

    <xs:complexType name="Types">
        <xs:sequence>
            <xs:element name="type" minOccurs="0" maxOccurs="unbounded" type="Type"/>
            <xs:element name="service" minOccurs="0" maxOccurs="unbounded" type="Service"/>
            <xs:element name="command" minOccurs="0" maxOccurs="unbounded" type="Command"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Service">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="required" type="availableBuilders"/>
                <xs:attribute name="key" use="optional" type="availableAccessors"/>
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Command">
        <xs:complexContent>
            <xs:extension base="Type"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Type">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="required" type="availableBuilders"/>
                <xs:attribute name="key" use="optional" type="xs:string"/>
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:complexContent mixed="true">
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:any minOccurs="0" processContents="skip"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Component">
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="availableBuilders">
        <xs:restriction base="xs:string">
            <xs:enumeration value="XSLTBuilder"/>
            <xs:enumeration value="CastorXMLBuilder"/>
            <xs:enumeration value="BeanShellBuilder"/>
            <xs:enumeration value="ClassBuilder"/>
            <xs:enumeration value="CachingClassBuilder"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="availableAccessors">
        <xs:restriction base="xs:string">
            <xs:enumeration value="com.ail.core.command.ClassAccessor"/>
            <xs:enumeration value="com.ail.core.command.BeanShellAccessor"/>
            <xs:enumeration value="com.ail.core.command.DroolsAccessor"/>
            <xs:enumeration value="com.ail.core.command.DroolsDecisionTableAccessor"/>
            <xs:enumeration value="com.ail.core.command.EJBAccessor"/>
            <xs:enumeration value="com.ail.core.command.WebServiceAccessor"/>
            <xs:enumeration value="com.ail.core.command.XSLTAccessor"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== heyguevara/open-quote/root/projects/openquote/1.4/core/core.ear/lib/core.jar/com/ail/core/CoreDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default (factory) configuration for the Core. This
 configuration is used by the core's resetConfiguration() method.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xmlns:xi="http://www.w3.org/2001/XInclude" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">

  <name>Default Core Configuration</name>
  <timeout>6000</timeout>
  <who>factory</who>
  <version>1.4</version>  

  <types>
    <!--====================================-->
    <!--   Define the default core services -->
    <!--====================================-->
    <service name="StyleDocumentService" builder="ClassBuilder" key="com.ail.core.command.XSLTAccessor">
      <parameter name="Url">classpath://com.ail.core.document.generatedocument/DefaultStyleDocumentService.xslt</parameter>
    </service>
          
    <!--=======================================================================-->
    <!-- Bind the default core services (above) to Commands used by Core.class -->
    <!--=======================================================================-->
    
    <!-- Map all of the logger commands to the stdio logger -->
    <command name="StyleDocumentCommand" builder="ClassBuilder" key="com.ail.core.document.generatedocument.StyleDocumentCommandImpl">
      <parameter name="Service">com.ail.core.logging.SystemOutLoggerService</parameter>
    </command>
    <command name="InfoLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggerCommandImpl">
      <parameter name="Service">com.ail.core.logging.SystemOutLoggerService</parameter>
    </command>
    <command name="DebugLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggerCommandImpl">
      <parameter name="Service">com.ail.core.logging.SystemOutLoggerService</parameter>
    </command>
    <command name="WarningLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggerCommandImpl">
      <parameter name="Service">com.ail.core.logging.SystemOutLoggerService</parameter>
    </command>
    <command name="ErrorLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggerCommandImpl">
      <parameter name="Service">com.ail.core.logging.SystemOutLoggerService</parameter>
    </command>
    <command name="FatalLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggerCommandImpl">
      <parameter name="Service">com.ail.core.logging.SystemOutLoggerService</parameter>
    </command>

    <!-- Map all of the persistence commands to hibernate -->
    <command name="OpenPersistenceSession" builder="ClassBuilder" key="com.ail.core.persistence.OpenSessionCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateOpenSessionService</parameter>
    </command>    
    <command name="ClosePersistenceSession" builder="ClassBuilder" key="com.ail.core.persistence.CloseSessionCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateCloseSessionService</parameter>
    </command>
    <command name="Update" builder="ClassBuilder" key="com.ail.core.persistence.UpdateCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateUpdateService</parameter>
    </command>
    <command name="Query" builder="ClassBuilder" key="com.ail.core.persistence.QueryCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateQueryService</parameter>
    </command>
    <command name="Load" builder="ClassBuilder" key="com.ail.core.persistence.LoadCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateLoadService</parameter>
    </command>    
    <command name="Create" builder="ClassBuilder" key="com.ail.core.persistence.CreateCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateCreateService</parameter>
    </command>
    <command name="Delete" builder="ClassBuilder" key="com.ail.core.persistence.DeleteCommandImpl">
      <parameter name="Service">com.ail.core.persistence.hibernate.HibernateDeleteService</parameter>
    </command>
    
  </types>
</configuration>

=== heyguevara/open-quote/projects/openquote/1.1/core/test.jar/com/ail/coretest/TestProductServicesDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 $Revision: 1.6 $
 $State: Exp $
 $Date: 2006/10/04 21:30:38 $
 $Source: /home/bob/CVSRepository/projects/core/test.jar/com/ail/coretest/TestProductServicesDefaultConfig.xml,v $
-->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>TestProduct default config</name>
    <timeout>600000</timeout>
    <who>factory</who>
    <version>$Revision: 1.6 $</version>

    <types>

        <!--====================================-->
        <!--   Define the component's services  -->
        <!--====================================-->

        <service name="CreateProductDefinitionService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.product.createproductdefinition.CreateProductDefinitionService</parameter>
        </service>
        <service name="DeleteProductDefinitionService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.product.deleteproductdefinition.DeleteProductDefinitionService</parameter>
        </service>
        <service name="GetProductDefinitionService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.product.getproductdefinition.GetProductDefinitionService</parameter>
        </service>
        <service name="GetProductDefinitionListService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.product.getproductdefinitionlist.GetProductDefinitionListService</parameter>
        </service>
        <service name="InstantiateProductService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.product.instantiateproduct.InstantiateProductService</parameter>
        </service>
        <service name="UpdateProductDefinitionService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.product.updateproductdefinition.UpdateProductDefinitionService</parameter>
        </service>


        <!--====================================-->
        <!--  Bind the commands to services     -->
        <!--====================================-->

        <command name="CreateProductDefinition" builder="ClassBuilder" key="com.ail.core.product.createproductdefinition.CreateProductDefinitionCommand">
            <parameter name="Service">CreateProductDefinitionService</parameter>
        </command>
        <command name="DeleteProductDefinition" builder="ClassBuilder" key="com.ail.core.product.deleteproductdefinition.DeleteProductDefinitionCommand">
            <parameter name="Service">DeleteProductDefinitionService</parameter>
        </command>
        <command name="GetProductDefinitionList" builder="ClassBuilder" key="com.ail.core.product.getproductdefinitionlist.GetProductDefinitionListCommand">
            <parameter name="Service">GetProductDefinitionListService</parameter>
        </command>
        <command name="GetProductDefinition" builder="ClassBuilder" key="com.ail.core.product.getproductdefinition.GetProductDefinitionCommand">
            <parameter name="Service">GetProductDefinitionService</parameter>
        </command>
        <command name="InstantiateProduct" builder="ClassBuilder" key="com.ail.core.product.instantiateproduct.InstantiateProductCommand">
            <parameter name="Service">InstantiateProductService</parameter>
        </command>
        <command name="UpdateProductDefinition" builder="ClassBuilder" key="com.ail.core.product.updateproductdefinition.UpdateProductDefinitionCommand">
            <parameter name="Service">UpdateProductDefinitionService</parameter>
        </command>

    </types>
</configuration>

=== heyguevara/open-quote/projects/openquote/2.0/modules/com/ail/core.jar/com/ail/core/CoreDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file defines the default (factory) configuration for the Core. This configuration is used by the core's resetConfiguration() 
    method. -->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <name>Default Core Configuration</name>
    <timeout>-1</timeout>
    <who>factory</who>
    <version>1.4</version>

    <!-- Next (unique) Number to use in unique number generation for the various -->
    <!-- types of number. The GenerateUniqueNumber service updates this parameter -->
    <!-- as numbers are used. These values can be overridden by product. -->
    <parameter name="InvoiceNumberNextNumber">1000</parameter>
    <parameter name="PolicyNumberNextNumber">1000</parameter>
    <parameter name="QuoteNumberNextNumber">1000</parameter>

    <!-- To avoid hitting the database every time a unique number is asked for, -->
    <!-- the GenerateUniqueNumber service takes a chunk of numbers at a time, -->
    <!-- keeps track of the ones it uses, then comes back for more when it runs -->
    <!-- out. *BlockSize controls the number that are allocated on each call. -->
    <!-- These values can be overridden by product. -->
    <parameter name="InvoiceNumberBlockSize">100</parameter>
    <parameter name="PolicyNumberBlockSize">100</parameter>
    <parameter name="QuoteNumberBlockSize">100</parameter>
    
    <group name="ProductURLHandler">
        <parameter name="Protocol">http</parameter>
        <parameter name="Host">localhost</parameter>
        <parameter name="Port">8080</parameter>
        <parameter name="Realm">PortalRealm</parameter>
        <parameter name="Path">/api/secure/webdav/guest/document_library/Product</parameter>
        <parameter name="Username">productreader@openquote.local</parameter>
        <parameter name="Password">productreader</parameter>
    </group>
    
    <group name="JEEAccessorContext">
        <!--
        In most deployments these settings are picked up from the server's environment, but in some
        circumstances it can be useful to override them - particularly if your client is accessing 
        remote EJBs.
        
        <parameter name="java.naming.factory.url.pkgs">org.jboss.ejb.client.naming</parameter>
        <parameter name="java.naming.factory.initial">org.jboss.naming.remote.client.InitialContextFactory</parameter>
        <parameter name="java.naming.provider.url">remote://localhost:4447</parameter>
        <parameter name="jboss.naming.client.ejb.context">true</parameter>
        <parameter name="java.naming.security.principal">openquote</parameter>
        <parameter name="java.naming.security.credentials">password</parameter>
        -->
    </group>

    <types>
        <service name='AcceptanceServicesEJB' builder='ClassBuilder' key='com.ail.core.command.EJBAccessor'>
            <parameter name='JndiName'>ejb:/acceptance-ejb//AcceptanceBean!com.ail.insurance.acceptance.AcceptanceLocal</parameter>
        </service>

        <service name="GenerateQuotationDocumentService" key="com.ail.core.command.EJBAccessor">
            <parameter name="JndiName">ejb:/quotation-ejb//QuotationBean!com.ail.insurance.quotation.QuotationLocal</parameter>
        </service>

        <service name="OnRiskEJB" key="com.ail.core.command.EJBAccessor">
            <parameter name="JndiName">ejb:/onrisk-ejb//OnRiskBean!com.ail.insurance.onrisk.OnRiskLocal</parameter>
        </service>

        <service name='PersistenceService' builder='ClassBuilder' key='com.ail.core.command.EJBAccessor'>
            <parameter name='JndiName'>ejb:/persistence-server-ejb//PersistenceServerBean!com.ail.core.persistence.PersistenceServerLocal</parameter>
        </service>

        <service name="JMSQueueService" key="com.ail.core.command.JMSAccessor">
            <parameter name="Factory">ConnectionFactory</parameter>
            <parameter name="Queue">queue/OpenQuoteCommandQueue</parameter>
        </service>

        <!-- Map all of the logger commands to the stdio logger -->
        <command name="InfoLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>
        <command name="DebugLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>
        <command name="WarningLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>
        <command name="ErrorLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>
        <command name="FatalLogger" builder="ClassBuilder" key="com.ail.core.logging.LoggingCommandImpl">
            <parameter name="Service">com.ail.core.logging.JavaLoggerService</parameter>
        </command>

        <!-- Map all of the persistence commands to the persistence server -->
        <command name="OpenPersistenceSession" builder="ClassBuilder" key="com.ail.core.persistence.OpenSessionCommandImpl">
            <parameter name="Service">PersistenceService</parameter>
        </command>
        <command name="ClosePersistenceSession" builder="ClassBuilder" key="com.ail.core.persistence.CloseSessionCommandImpl">
            <parameter name="Service">PersistenceService</parameter>
        </command>
        <command name="Update" builder="ClassBuilder" key="com.ail.core.persistence.UpdateCommandImpl">
            <parameter name="Service">PersistenceService</parameter>
        </command>
        <command name="Query" builder="ClassBuilder" key="com.ail.core.persistence.QueryCommandImpl">
            <parameter name="Service">PersistenceService</parameter>
        </command>
        <command name="Load" builder="ClassBuilder" key="com.ail.core.persistence.LoadCommandImpl">
            <parameter name="Service">PersistenceService</parameter>
        </command>
        <command name="Create" builder="ClassBuilder" key="com.ail.core.persistence.CreateCommandImpl">
            <parameter name="Service">PersistenceService</parameter>
        </command>
        <command name="Delete" builder="ClassBuilder" key="com.ail.core.persistence.DeleteCommandImpl">
            <parameter name="Service">PersistenceService</parameter>
        </command>

        <command name='FetchQuoteDocument' builder='ClassBuilder' key='com.ail.insurance.quotation.FetchDocumentCommandImpl'>
            <parameter name='Service'>com.ail.insurance.quotation.fetchdocument.FetchDocumentService</parameter>
        </command>
        
        <command name='GenerateQuotationDocument' builder='ClassBuilder' key='com.ail.insurance.quotation.GenerateDocumentCommandImpl'>
            <parameter name='Service'>GenerateQuotationDocumentService</parameter>
        </command>
        <command name='GenerateWordingDocument' builder='ClassBuilder' key='com.ail.insurance.onrisk.GenerateWordingCommandImpl'>
            <parameter name='Service'>OnRiskEJB</parameter>
        </command>
        <command name='GenerateCertificateDocument' builder='ClassBuilder' key='com.ail.insurance.onrisk.GenerateCertificateCommandImpl'>
            <parameter name='Service'>OnRiskEJB</parameter>
        </command>
        <command name='GenerateInvoiceDocument' builder='ClassBuilder' key='com.ail.insurance.onrisk.GenerateInvoiceCommandImpl'>
            <parameter name='Service'>OnRiskEJB</parameter>
        </command>

        <command name="AcceptQuotation" builder="ClassBuilder" key="com.ail.insurance.acceptance.AcceptQuotationCommandImpl">
            <parameter name="Service">AcceptanceServicesEJB</parameter>
        </command>

        <command name="QueuedClearProductCacheCommand" builder="ClassBuilder" key="com.ail.core.product.ClearProductCacheCommandImpl">
            <parameter name="Service">JMSQueueService</parameter>
        </command>
        <command name="QueuedResetProductCommand" builder="ClassBuilder" key="com.ail.core.product.ResetProductCommandImpl">
            <parameter name="Service">JMSQueueService</parameter>
        </command>
    </types>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/2.0-defunct-1/insurance/test.jar/com/ail/insurancetest/TestAcceptanceDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 $Revision: 1.3 $
 $State: Exp $
 $Date: 2006/10/04 22:03:13 $
 $Source: /home/bob/CVSRepository/projects/insurance/test.jar/com/ail/insurancetest/TestAcceptanceDefaultConfig.xml,v $
-->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Default Service Invocation Configuration</name>
  <timeout>600000</timeout>
  <who>factory</who>
  <version>$Revision: 1.3 $</version>
  <types>
    <!--====================================-->
    <!--   Define the component's services  -->
    <!--====================================-->
    <service name="AcceptanceComponent" builder="ClassBuilder" key="com.ail.core.command.EJBAccessor">
      <parameter name="JndiName">Acceptance</parameter>
    </service>
    
    <!--=======================================================================-->
    <!-- Bind the default core services (above) to Commands used by Core.class -->
    <!--=======================================================================-->
    <command name="PutOnRiskService" builder="ClassBuilder" key="com.ail.insurance.acceptance.PutOnRiskCommand">
      <parameter name="Service">AcceptanceComponent</parameter>
    </command>
    <command name="ProduceDocumentationService" builder="ClassBuilder" key="com.ail.insurance.acceptance.ProduceDocumentationCommand">
      <parameter name="Service">AcceptanceComponent</parameter>
    </command>
    <command name="CollectPremiumService" builder="ClassBuilder" key="com.ail.insurance.acceptance.CollectPremiumCommand">
      <parameter name="Service">AcceptanceComponent</parameter>
    </command>
  </types>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/1.4/insurance/insurance.ear/lib/insurance.jar/com/ail/core/product/Product/RegistryDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This is the 'Base' product used in testing the insurance product
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">
    <name>Configuration for the Base product</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>$Revision$</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    
    <!-- Select the method used to generate new numbers. Options are:                            -->
    <!--  ConfigurePropertyUniqueNumberHandler - which stores the numbers in configuation.       -->
    <!--  PolicyIdUniqueNumberGeneratorHandler - use the policy's unique ID as the quote number. -->
    <parameter name="UniqueQuotationNumberHandler">ConfigurePropertyUniqueNumberHandler</parameter>

    <!-- Next (unique) Number to use in policy number generation. The service -->
    <!-- updates this parameter as numbers are used up.                       -->
    <parameter name="NextPolicyNumber">1000</parameter>
    
    <!-- To avoid hitting the database every time a policy number is asked for, -->
    <!-- the service takes a chunk of numbers at a time, keeps track of the     -->
    <!-- ones it uses, then comes back for more when it runs out. BlockSize     -->
    <!-- controls the number that are allocated on each call.                   -->
    <parameter name="PolicyNumberBlockSize">100</parameter>

    <types>
        <service name="PolicyRule" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor" >
            <parameter name="Script"><![CDATA[
import com.ail.financial.CurrencyAmount;
import com.ail.financial.Currency;
import com.ail.insurance.policy.*;

/* get hold of the as */
as=args.getAssessmentSheetArgRet();

/* add a 'flag' - just to show that this rule has been run */
line=new FixedSum();
line.setId("flag");
line.setAmount(new CurrencyAmount(0.0, Currency.GBP));
as.addLine(line);
                ]]></parameter>
        </service>
        
        <service name="GeneratePolicyNumber" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor">
            <parameter name="Script"><![CDATA[
args.setPolicyNumberRet("POL"+args.getUniqueNumberArg());
             ]]></parameter>
        </service>
        
        <service name="GenerateQuoteNumber" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor">
            <parameter name="Script"><![CDATA[
args.setQuoteNumberRet("QF"+args.getUniqueNumberArg());
         ]]></parameter>
        </service>

        <!-- Risk assessment rules (command & service) for all products unless they override -->
        <command name="AssessPolicyRisk" builder="ClassBuilder" key="com.ail.insurance.quotation.assessrisk.AssessPolicyRiskCommandImpl">
            <parameter name="Service">PolicyRule</parameter>
        </command>

        <!-- Tax calc rules (command & service) for this product. By default, no taxes are applied -->
        <command name="CalculatePolicyTax" builder="ClassBuilder" key="com.ail.insurance.quotation.calculatetax.CalculatePolicyTaxCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>
        
        <!-- Commission calc rules (command & service) for this product. By default, no commissions are applied -->
        <command name="CalculatePolicyCommission" builder="ClassBuilder" key="com.ail.insurance.quotation.calculatecommission.CalculatePolicyCommissionCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>

        <!-- Brokerage calc rules (command & service) for this product. By default, no brokerage is applied -->
        <command name="CalculatePolicyBrokerage" builder="ClassBuilder" key="com.ail.insurance.quotation.calculatebrokerage.CalculatePolicyBrokerageCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>
        
        <!-- Management charge rules (command & service) for this product. By default, no charges are applied -->
        <command name="CalculatePolicyMgmtChg" builder="ClassBuilder" key="com.ail.insurance.quotation.calculatemanagementcharge.CalculatePolicyMgmtChgCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>

        <!-- Generate policy number default command & service. -->
        <command name="GeneratePolicyNumberRule" builder="ClassBuilder" key="com.ail.insurance.quotation.addpolicynumber.GeneratePolicyNumberRuleCommandImpl">
            <parameter name="Service">GeneratePolicyNumber</parameter>
        </command>
        <!-- Generate quote number default command & service. -->
        <command name="GenerateQuoteNumberRule" builder="ClassBuilder" key="com.ail.insurance.quotation.addquotenumber.GenerateQuoteNumberRuleCommandImpl">
            <parameter name="Service">GenerateQuoteNumber</parameter>
        </command>

        <!-- Enforce compliance rules (command & service). By default, no rules are applied -->
        <command name="EnforcePolicyCompliance" builder="ClassBuilder" key="com.ail.insurance.quotation.enforcecompliance.EnforcePolicyComplianceCommandImpl">
            <parameter name="Service">com.ail.core.NullService</parameter>
        </command>        
    </types>
</configuration>
