=== heyguevara/open-quote/projects/openquote/1.2/core/core.ear/configure.war/schemas/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <xs:element name="configuration" type="Configuration"/>

    <xs:complexType name="Configuration">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="parentNamespace" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="who" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="manager" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="group" minOccurs="0" maxOccurs="unbounded" type="Group"/>
            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter"/>
            <xs:element name="builders" minOccurs="0" maxOccurs="1" type="Builders"/>
            <xs:element name="types" minOccurs="0" maxOccurs="1" type="Types"/>
        </xs:sequence>
        <xs:attribute name="timeout" use="required" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="Group">
        <xs:complexContent>
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="Parameter"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
     </xs:complexType>

    <xs:complexType name="Builders">
        <xs:sequence>
            <xs:element name="builder" maxOccurs="unbounded" type="Builder"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Builder">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="factory" use="required" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
     </xs:complexType>

    <xs:complexType name="Types">
        <xs:sequence>
            <xs:element name="type" minOccurs="0" maxOccurs="unbounded" type="Type"/>
            <xs:element name="service" minOccurs="0" maxOccurs="unbounded" type="Service"/>
            <xs:element name="command" minOccurs="0" maxOccurs="unbounded" type="Command"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Service">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="required" type="availableBuilders"/>
                <xs:attribute name="key" use="optional" type="availableAccessors"/>
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Command">
        <xs:complexContent>
            <xs:extension base="Type"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Type">
        <xs:complexContent>
            <xs:extension base="Group">
                <xs:attribute name="builder" use="required" type="availableBuilders"/>
                <xs:attribute name="key" use="optional" type="xs:string"/>
                <xs:attribute name="singleInstance" use="optional" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Parameter">
        <xs:complexContent mixed="true">
            <xs:extension base="Component">
                <xs:sequence>
                    <xs:any minOccurs="0" processContents="skip"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Component">
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="availableBuilders">
        <xs:restriction base="xs:string">
            <xs:enumeration value="XSLTBuilder"/>
            <xs:enumeration value="CastorXMLBuilder"/>
            <xs:enumeration value="BeanShellBuilder"/>
            <xs:enumeration value="ClassBuilder"/>
            <xs:enumeration value="CachingClassBuilder"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="availableAccessors">
        <xs:restriction base="xs:string">
            <xs:enumeration value="com.ail.core.command.ClassAccessor"/>
            <xs:enumeration value="com.ail.core.command.BeanShellAccessor"/>
            <xs:enumeration value="com.ail.core.command.DroolsAccessor"/>
            <xs:enumeration value="com.ail.core.command.DroolsDecisionTableAccessor"/>
            <xs:enumeration value="com.ail.core.command.EJBAccessor"/>
            <xs:enumeration value="com.ail.core.command.WebServiceAccessor"/>
            <xs:enumeration value="com.ail.core.command.XSLTAccessor"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== heyguevara/open-quote/root/projects/openquote/1.3/openquote/openquote.ear/command-server-ejb.jar/com/ail/core/command/CommandServerDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default (factory) configuration for the Rainbow
 component. This configuration is used by the component's resetConfiguration()
 method.
-->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>CommandServerBean configuration</name>
    <timeout>-1</timeout>
    <who>factory</who>
    <version>$Revision$</version>

    <types>
        <service name="NotifyBrokerByEmailService" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.insurance.quotation.notifybrokerbyemail.NotifyBrokerByEmailService</parameter>
        </service>

        <command name="NotifyBrokerByEmailArgImp" key="com.ail.insurance.quotation.notifybrokerbyemail.NotifyBrokerByEmailCommand">
            <parameter name="Service">NotifyBrokerByEmailService</parameter>
        </command>
    </types>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/2.0/core/core.ear/configure-server-ejb.jar/com/ail/core/configure/server/ServerDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default (factory) configuration for the Rainbow
 component. This configuration is used by the component's resetConfiguration()
 method.
 $Revision: 1.6 $
 $State: Exp $
 $Date: 2006/10/04 21:30:38 $
 $Source: /home/bob/CVSRepository/projects/core/core.ear/configure-server-ejb.jar/com/ail/core/configure/server/ServerDefaultConfig.xml,v $
-->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Configure ServerBean configuration</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>$Revision: 1.6 $</version>

    <types>

        <!--====================================-->
        <!--   Define the component's services  -->
        <!--====================================-->
        <service name="GetNamespacesService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.configure.server.GetNamespacesService</parameter>
        </service>
        <service name="GetConfigurationService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.configure.server.GetConfigurationService</parameter>
        </service>
        <service name="SetConfigurationService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.configure.server.SetConfigurationService</parameter>
        </service>
        <service name="GetCommandScriptService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.configure.server.GetCommandScriptService</parameter>
        </service>
        <service name="SetCommandScriptService" builder="ClassBuilder" key="com.ail.core.command.ClassAccessor">
            <parameter name="ServiceClass">com.ail.core.configure.server.SetCommandScriptService</parameter>
        </service>

        <!--=======================================================================-->
        <!-- Bind the default core services (above) to Commands used by Core.class -->
        <!--=======================================================================-->
        <command name="GetNamespaces" builder="ClassBuilder" key="com.ail.core.configure.server.GetNamespacesCommand">
            <parameter name="Service">GetNamespacesService</parameter>
        </command>
        <command name="GetConfiguration" builder="ClassBuilder" key="com.ail.core.configure.server.GetConfigurationCommand">
            <parameter name="Service">GetConfigurationService</parameter>
        </command>
        <command name="SetConfiguration" builder="ClassBuilder" key="com.ail.core.configure.server.SetConfigurationCommand">
            <parameter name="Service">SetConfigurationService</parameter>
        </command>
        <command name="GetCommandScript" builder="ClassBuilder" key="com.ail.core.configure.server.GetCommandScriptCommand">
            <parameter name="Service">GetCommandScriptService</parameter>
        </command>
        <command name="SetCommandScript" builder="ClassBuilder" key="com.ail.core.configure.server.SetCommandScriptCommand">
            <parameter name="Service">SetCommandScriptService</parameter>
        </command>
    </types>
</configuration>

=== heyguevara/open-quote/root/projects/openquote/1.0/core/core.ear/lib/core.jar/com/ail/core/product/TestProduct2/RegistryDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines a test product for use in the core system. This product configuration is
 required in live deployments and is only used for testing purposes.
 $Revision$
 $Author$
 $State$
 $Date$
 $Source$
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">
    <name>Configuration for Test Product 2</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>$Revision$</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    <parentNamespace>com.ail.core.product.TestProduct1.Registry</parentNamespace>
    
    <parameter name="TestPropertyA">Product 2's A Value</parameter>
    <parameter name="TestPropertyC">C's Value</parameter>
    
    <types>
        <type name="TestProduct2" key="com.ail.core.Type" builder="CastorXMLBuilder">
            <parameter name="Script"><![CDATA[
               <type xsi:type='java:com.ail.core.Type' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
                  <attribute id="name" type="string" value="TestProduct2"/>
                  <attribute id="productname" type="string" value="TestProduct2"/>
                  <attribute id="age" type="number" value="34"/>
                  <attribute id="colour" type="string" value="purple"/>
               </type>
            ]]></parameter>
        </type>
        
        <type name="TestTypeB" key="com.ail.core.Type" builder="BeanShellBuilder">
            <parameter name="Extends">TestTypeA</parameter>
            <parameter name="Script"><![CDATA[
                type=new com.ail.core.Type();
                
                a=new com.ail.core.Attribute();
                a.setId("name");
                a.setValue("TestTypeB");
                type.addAttribute(a);
                
                a=new com.ail.core.Attribute();
                a.setId("colour");
                a.setValue("TestTypeB");
                type.addAttribute(a);
            ]]></parameter>
        </type>
    </types>
    
</configuration>

=== heyguevara/open-quote/root/projects/openquote/1.4/insurance/integration-test.jar/com/ail/core/product/TestProduct1/RegistryDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines a test product for use in the core system. This product configuration is
 required in live deployments and is only used for testing purposes.
-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">
    <name>Configuration for Test Product 1</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>$Revision$</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>
    <parentNamespace>com.ail.core.product.Product.Registry</parentNamespace>
    
    <!-- Select the method used to generate new numbers. Options are:                            -->
    <!--  ConfigurePropertyUniqueNumberHandler - which stores the numbers in configuation.       -->
    <!--  PolicyIdUniqueNumberGeneratorHandler - use the policy's unique ID as the quote number. -->
    <parameter name="UniqueQuotationNumberHandler">ConfigurePropertyUniqueNumberHandler</parameter>

    <types>
        <service name="AssessRiskRules" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor">
            <parameter name="Script"><![CDATA[
                import com.ail.financial.CurrencyAmount;
                import com.ail.financial.Currency;
                import com.ail.util.Rate;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                /* add a 'sum insured' for 500.00 GBP*/
                line=new FixedSum();
                line.setId("sum insured");
                line.setAmount(new CurrencyAmount(500.00, Currency.GBP));
                as.addLine(line);
                
                /* add a loading of 5% for no reason! */
                line=new RateBehaviour();
                line.setId("loading1");
                line.setDependsOn("sum insured");
                line.setContributesTo("policy.total premium");
                line.setRate(new Rate("50%"));;
                line.setType(BehaviourType.LOAD);
                line.setReason("No reason what so ever!");
                as.addLine(line);
            ]]></parameter>
        </service>

        <service name="TaxCalcRules" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor" >
            <parameter name="Script"><![CDATA[
                import com.ail.util.*;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                /* add a 15% tax line */
                line=new RateBehaviour("tax", "Insurance Tax", null, "policy.total premium", "sec1.sum insured", BehaviourType.TAX, new Rate("15%"));
                as.addLine(line);
            ]]></parameter>
        </service>        

        <service name="CommissionCalcRules" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor" >
            <parameter name="Script"><![CDATA[
                import com.ail.util.*;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                /* add a 1% commission */
                line=new RateBehaviour("commission1", "Commission", null, "policy.total premium", "sec1.sum insured", BehaviourType.COMMISSION, new Rate("1%"));
                as.addLine(line);
            ]]></parameter>
        </service>
        
        <service name="BrokerageCalcRules" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor">
            <parameter name="Script"><![CDATA[
                import com.ail.util.*;
                import com.ail.insurance.policy.*;
                
                /* get hold of the as */
                as=args.getAssessmentSheetArgRet();
                
                /* add a 15% tax line */
                line=new RateBehaviour("brokerage", "Brokerage", null, "policy.total premium", "sec1.sum insured", BehaviourType.BROKERAGE, new Rate("0.5%"));
                as.addLine(line);
            ]]></parameter>
        </service>
        
        
        <service name="MgmtChgRules" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor">
            <parameter name="Script"><![CDATA[
                import com.ail.util.*;
                import com.ail.insurance.policy.*;
                
                as=args.getAssessmentSheetArgRet();
                line=new RateBehaviour("charge", "Management charge", null, "policy.total premium", "sec1.sum insured", BehaviourType.MANAGEMENT_CHARGE, new Rate("0.025%"));
                as.addLine(line);
            ]]></parameter>
        </service>

        <!-- Risk assessment rules (command & service) for this product -->
        <command name="AssessSectionRisk/TestSectionID" builder="ClassBuilder" key="com.ail.insurance.quotation.assessrisk.AssessSectionRiskCommandImpl">
            <parameter name="Service">AssessRiskRules</parameter>
        </command>

        <!-- Tax calc rules (command & service) for this product -->
        <command name="CalculatePolicyTax" builder="ClassBuilder" key="com.ail.insurance.quotation.calculatetax.CalculatePolicyTaxCommandImpl">
            <parameter name="Service">TaxCalcRules</parameter>
        </command>

        <!-- Commission calc rules (command & service) for this product -->
        <command name="CalculatePolicyCommission" builder="ClassBuilder" key="com.ail.insurance.quotation.calculatecommission.CalculatePolicyCommissionCommandImpl">
            <parameter name="Service">CommissionCalcRules</parameter>
        </command>

        <!-- Brokerage calc rules (command & service) for this product -->
        <command name="CalculatePolicyBrokerage" builder="ClassBuilder" key="com.ail.insurance.quotation.calculatebrokerage.CalculatePolicyBrokerageCommandImpl">
            <parameter name="Service">BrokerageCalcRules</parameter>
        </command>

        <!-- Management cgarge rules (command & service) for this product -->
        <command name="CalculatePolicyMgmtChg" builder="ClassBuilder" key="com.ail.insurance.quotation.calculatemanagementcharge.CalculatePolicyMgmtChgCommandImpl">
            <parameter name="Service">MgmtChgRules</parameter>
        </command>

        <type name="TestProduct1" key="com.ail.core.Type" builder="BeanShellBuilder">
            <parameter name="Script"><![CDATA[
                import com.ail.insurance.policy.*;
                
                policy=new Policy();
                policy.setProductTypeId("com.ail.core.product.TestProduct1");
                section=new Section();
                section.setId("sec1");
                section.setSectionTypeId("TestSectionID");
                policy.addSection(section);
                policy.setStatus(PolicyStatus.APPLICATION);
                type=policy;
            ]]></parameter>
        </type>
    </types>
</configuration>

=== heyguevara/open-quote/projects/openquote/1.1/insurance/insurance.ear/lib/insurance.jar/com/ail/insurance/quotation/addquotenumber/AddQuoteNumberDefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 This file defines the default (factory) configuration for the
 AddQuoteNumber Service. This configuration is used by the entry point's
 resetConfiguration() method.
 This configuration doesn't represent a real live configuration. This
 is only the core service and as such it doesn't define any product
 rules. For these you have to look at the specialisations that use this
 service.
 $Revision: 1.4 $
 $State: Exp $
 $Date: 2006/10/04 22:03:15 $
 $Source: /home/bob/CVSRepository/projects/insurance/insurance.ear/insurance.jar/com/ail/insurance/quotation/addquotenumber/AddQuoteNumberDefaultConfig.xml,v $
-->
<configuration xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>CalculateTax service default configuration</name>
    <timeout>60000</timeout>
    <who>factory</who>
    <version>$Revision: 1.4 $</version>
    
    <!-- Select the method used to generate new numbers. Options are:                            -->
    <!--  ConfigurePropertyUniqueNumberHandler - which stores the numbers in configuation.       -->
    <!--  PolicyIdUniqueNumberGeneratorHandler - use the policy's unique ID as the quote number. -->
    <parameter name="UniqueQuotationNumberHandler">ConfigurePropertyUniqueNumberHandler</parameter>
    
    <!-- Next (unique) Number to use in quote number generation. The service -->
    <!-- updates this parameter as numbers are used up.                      -->
    <parameter name="NextNumber">1000</parameter>
    
    <!-- To avoid hitting the database every time a quote number is asked for, -->
    <!-- the service takes a chunk of numbers at a time, keeps track of the    -->
    <!-- ones it uses, then comes back for more when it runs out. BlockSize    -->
    <!-- controls the number that are allocated on each call.                  -->
    <parameter name="BlockSize">100</parameter>
</configuration>

=== heyguevara/open-quote/projects/openquote/1.1/openquote/content/export_versions.acp/export_versions/content37.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="http://www.appliedindustriallogic.com/schemas/Configuration.xsd">
    <timeout>-1</timeout>
    <name>Equine Plus product configuration</name>
    <parentNamespace>AIL.Base.Registry</parentNamespace>
    <who>Applied Industrial Logic</who>
    <version>1.0</version>
    <manager>com.ail.core.product.resetproduct.ResetProductService</manager>

    <types>
        
        <service name="AssessPolicyRiskRule" builder="CachingClassBuilder" key="com.ail.core.command.DroolsDecisionTableAccessor" >
            <parameter name="Url">~/PolicyRating.xls</parameter>
        </service>

        <service name="CalculatePolicyCommissionRule" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor">
            <parameter name="Url">~/CalculateCommission.bs</parameter>
        </service>

        <service name="CalculatePolicyMgmtChgRule" builder="ClassBuilder" key="com.ail.core.command.BeanShellAccessor">
            <parameter name="Url">~/CalculateManagementCharge.bs</parameter>
        </service>
        
        <service name="StyleDocumentService" builder="ClassBuilder" key="com.ail.core.command.XSLTAccessor">
            <parameter name="Url">http://localhost:8080/portal-core/themes/industrial/style.xslt</parameter>
        </service>

        <command name="AssessSectionRisk/EquinePlusSection" builder="CachingClassBuilder" key="com.ail.insurance.quotation.assessrisk.AssessSectionRiskCommand">
            <parameter name="Service">NullService</parameter>
        </command>
        
        <type name="Quotation" builder="BeanShellBuilder">
            <parameter name="extends">BaseQuotation</parameter>
            <parameter name="Url">~/Quotation.bs</parameter>
        </type>
        
        <!-- Equine section  -->
        <type name="EquinePlusSection" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Section">
            <parameter name="Url">~/EquinePlusSection.xml</parameter>
        </type>
        
        <type name="SaddleryAndTackExcess" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Excess">
            <parameter name="Url">~/SaddleryAndTackExcess.xml</parameter>
        </type>
        
        <type name="HorseAsset" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Asset">
            <parameter name="Url">~/HorseAsset.xml</parameter>
        </type>
        
        <type name="CoverageAsset" builder="CastorXMLBuilder" key="com.ail.insurance.policy.Asset">
            <parameter name="Url">~/CoverageAsset.xml</parameter>
        </type>
        
        <type name="HorseAge" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.openquote.ui.util.Choice"> 
            <parameter name="Url">~/HorseAge.xml</parameter>
        </type>
        
        <type name="HorseColour" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.openquote.ui.util.Choice">
            <parameter name="Url">~/HorseColour.xml</parameter>
        </type>
        
        <type name="HorseHeightHands" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.openquote.ui.util.Choice">
            <parameter name="Url">~/HorseHeightHands.xml</parameter>
        </type>
        
        <type name="QuotationPageFlow" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.openquote.ui.PageFlow">
            <parameter name="Url">~/QuotationPageFlow.xml</parameter>
        </type>

        <type name="QuotationDocument" builder="CastorXMLBuilder" singleInstance="true" key="com.ail.core.document.model.DocumentDefinition">
            <parameter name="Url">~/QuotationDocument.xml</parameter>
        </type>
        
    </types>
</configuration>
